# Wrangler 配置文件 - 多用户Token池管理系统
name = "augment2api-proxy-dual-v1"
main = "src/worker-multiuser.js"
compatibility_date = "2024-01-01"

# 环境变量
[vars]
# 系统配置
ENVIRONMENT = "development"
API_VERSION = "v1.0.0"
DEFAULT_TOKEN_QUOTA = "3"
MAX_TOKEN_QUOTA = "10"
SESSION_EXPIRE_HOURS = "24"
RATE_LIMIT_PER_HOUR = "1000"

# 管理员配置（开发环境）
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "admin123"  # 生产环境中应使用强密码

# 兼容性配置（保留原有功能）
UNIFIED_TOKEN = "your-unified-token-here"
ACCESS_PWD = "admin-password-123"

# D1 数据库绑定 - 部署后需要手动绑定
# [[d1_databases]]
# binding = "DB"
# database_name = "augment2api-multiuser"
# database_id = ""

# 生产环境配置
[env.production]
name = "augment2api-proxy-prod"

[env.production.vars]
UNIFIED_TOKEN = "your-production-unified-token"
ACCESS_PWD = "your-production-admin-password"

[[env.production.d1_databases]]
binding = "DB"
database_name = "augment"
database_id = "7e2841ef-9e67-4ce6-bb2f-3af21664c77f"

# 测试环境配置
[env.staging]
name = "augment2api-proxy-staging"

[env.staging.vars]
UNIFIED_TOKEN = "your-staging-unified-token"
ACCESS_PWD = "your-staging-admin-password"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "augment"
database_id = "7e2841ef-9e67-4ce6-bb2f-3af21664c77f"
